spring:
  application:
    name: DbMetadataExtractionApp
    
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
         
h2:
  datasource:
    url: jdbc:h2:mem:meta_extractor
    driver-class-name: org.h2.Driver
    username: root
    password:

mysql:
  datasource:
    url: jdbc:mysql://localhost:3306/meta_extractor
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

      
      